/**
 * Bareeq café menu — structured product knowledge base.
 * Names and prices match the official menu.
 */
import { defineProduct } from "./product.js";

/** @param {Parameters<typeof defineProduct>[0]} fields */
function menuItem(fields) {
  return defineProduct({
    currency: "EGP",
    image: "",
    availability: true,
    recommendable: true,
    ...fields,
  });
}

const rawProducts = [
  menuItem({
    id: "bq-fruity-ice-chocolate",
    nameEn: "Fruity Ice Chocolate",
    nameAr: "شوكولاتة مثلجة بالفواكه",
    category: "drink",
    price: 120,
    descriptionAr: "فواكه وشوكولاتة مثلجة.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-tropical-hibiscus",
    nameEn: "tropical Hibiscus",
    nameAr: "كركديه استوائي",
    category: "drink",
    price: 100,
    descriptionAr: "مشروب كركديه استوائي منعش.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-strawberry-hot-chocolate",
    nameEn: "Strawberry hot chocolate",
    nameAr: "شوكولاتة ساخنة بالفراولة",
    category: "drink",
    price: 100,
    descriptionAr: "شوكولاتة ساخنة بنكهة الفراولة.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-bueno-hot-chocolate",
    nameEn: "Bueno Hot Chocolate",
    nameAr: "شوكولاتة ساخنة بوينو",
    category: "drink",
    price: 100,
    descriptionAr: "شوكولاتة ساخنة بنكهة بوينو.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-aero-press",
    nameEn: "Aero press",
    nameAr: "إيرو بريس",
    category: "coffee",
    price: 100,
    descriptionAr: "قهوة مخمرة بطريقة الإيرو بريس.",
    temperature: "hot",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-v60",
    nameEn: "V60",
    nameAr: "في٦٠",
    category: "coffee",
    price: 120,
    descriptionAr: "قهوة فيلتر بطريقة V60.",
    temperature: "hot",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-vanilla-spice-latte",
    nameEn: "Vanilla Spice Latte",
    nameAr: "لاتيه فانيليا وتوابل",
    category: "coffee",
    price: 120,
    descriptionAr: "حليب طازج، قرفة، فانيليا وإسبريسو.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-turkish-coffee-cup",
    nameEn: "قهوة تركي",
    nameAr: "قهوة تركي",
    category: "coffee",
    price: 35,
    descriptionAr: "قهوة تركي تقليدية.",
    temperature: "hot",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-medjool-date-latte",
    nameEn: "Medjool Date Latte",
    nameAr: "لاتيه تمر مجدول",
    category: "coffee",
    price: 120,
    descriptionAr: "تمر مجدول، إسبريسو، حليب طازج ولمسة قرفة.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-pistachio-latte",
    nameEn: "Pistachio Latte",
    nameAr: "لاتيه فستق",
    category: "coffee",
    price: 130,
    descriptionAr: "فستق، حليب طازج وإسبريسو.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-spanish-latte",
    nameEn: "Spanish Latte",
    nameAr: "لاتيه إسباني",
    category: "coffee",
    price: 115,
    descriptionAr: "حليب مكثف، إسبريسو وحليب.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
    dessertPairing: ["bq-red-velvet-cake"],
  }),
  menuItem({
    id: "bq-white-mocha",
    nameEn: "White Mocha",
    nameAr: "وايت موكا",
    category: "coffee",
    price: 115,
    descriptionAr: "وايت موكا، إسبريسو وحليب.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-mocha",
    nameEn: "Mocha",
    nameAr: "موكا",
    category: "coffee",
    price: 115,
    descriptionAr: "شوكولاتة، حليب طازج وإسبريسو.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-macchiato",
    nameEn: "Macchiato",
    nameAr: "ماكياتو",
    category: "coffee",
    price: 60,
    descriptionAr: "إسبريسو مع لمسة رغوة خفيفة.",
    temperature: "hot",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-salted-caramel-latte",
    nameEn: "Salted Caramel Latte",
    nameAr: "لاتيه كراميل مملح",
    category: "coffee",
    price: 115,
    descriptionAr: "حليب طازج، إسبريسو وكراميل مملح.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-cappuccino",
    nameEn: "Cappuccino",
    nameAr: "كابتشينو",
    category: "coffee",
    price: 85,
    descriptionAr: "حليب طازج، إسبريسو ورغوة.",
    temperature: "hot",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-latte",
    nameEn: "Latte",
    nameAr: "لاتيه",
    category: "coffee",
    price: 100,
    descriptionAr: "حليب طازج وإسبريسو.",
    temperature: "hot",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-cortado",
    nameEn: "Cortado",
    nameAr: "كورتادو",
    category: "coffee",
    price: 70,
    descriptionAr: "إسبريسو وحليب مع لمسة رغوة.",
    temperature: "hot",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-hot-caramel-macchiato",
    nameEn: "Hot Caramel Macchiato",
    nameAr: "كراميل ماكياتو ساخن",
    category: "coffee",
    price: 115,
    descriptionAr: "كراميل، حليب طازج وإسبريسو.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-flat-white",
    nameEn: "Flat White",
    nameAr: "فلات وايت",
    category: "coffee",
    price: 80,
    descriptionAr: "إسبريسو وحليب مع لمسة رغوة.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
    dessertPairing: ["bq-butter-croissant"],
  }),
  menuItem({
    id: "bq-cinnamon-caramel-latte",
    nameEn: "Cinnamon Caramel Latte",
    nameAr: "لاتيه كراميل بالقرفة",
    category: "coffee",
    price: 115,
    descriptionAr: "كراميل، قرفة، حليب طازج وإسبريسو.",
    temperature: "hot",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-americano",
    nameEn: "Americano",
    nameAr: "أمريكانو",
    category: "coffee",
    price: 70,
    descriptionAr: "إسبريسو وماء ساخن.",
    temperature: "hot",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-espresso",
    nameEn: "Espresso",
    nameAr: "إسبريسو",
    category: "coffee",
    price: 60,
    descriptionAr: "قهوة سبيشيالتي.",
    temperature: "hot",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-iced-americano",
    nameEn: "Iced Americano",
    nameAr: "أمريكانو مثلج",
    category: "coffee",
    price: 70,
    descriptionAr: "إسبريسو مثلج.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-iced-pistachio-latte",
    nameEn: "Iced Pistachio Latte",
    nameAr: "لاتيه فستق مثلج",
    category: "coffee",
    price: 130,
    descriptionAr: "فستق، حليب طازج وإسبريسو.",
    temperature: "iced",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-iced-caramel-macchiato",
    nameEn: "Iced Caramel Macchiato",
    nameAr: "كراميل ماكياتو مثلج",
    category: "coffee",
    price: 115,
    descriptionAr: "صلصة كراميل، حليب طازج وإسبريسو.",
    temperature: "iced",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-iced-shaken-white-mocha",
    nameEn: "Iced Shaken White Mocha",
    nameAr: "وايت موكا مثلج مهزوز",
    category: "coffee",
    price: 115,
    descriptionAr: "وايت موكا، إسبريسو وحليب طازج.",
    temperature: "iced",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-iced-mocha",
    nameEn: "Iced Mocha",
    nameAr: "موكا مثلجة",
    category: "coffee",
    price: 115,
    descriptionAr: "شوكولاتة، إسبريسو وحليب طازج.",
    temperature: "iced",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-iced-salted-caramel-latte",
    nameEn: "Iced Salted Caramel Latte",
    nameAr: "لاتيه كراميل مملح مثلج",
    category: "coffee",
    price: 115,
    descriptionAr: "حليب طازج، إسبريسو وكراميل مملح.",
    temperature: "iced",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-iced-spanish-latte",
    nameEn: "Iced Spanish Latte",
    nameAr: "لاتيه إسباني مثلج",
    category: "coffee",
    price: 115,
    descriptionAr: "حليب طازج، إسبريسو وحليب مكثف.",
    temperature: "iced",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-iced-latte",
    nameEn: "Iced Latte",
    nameAr: "لاتيه مثلج",
    category: "coffee",
    price: 100,
    descriptionAr: "حليب طازج، إسبريسو وثلج.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-peanut-butter-blend",
    nameEn: "Peanut Butter Blend",
    nameAr: "بليند زبدة فول سوداني",
    category: "blended",
    price: 120,
    descriptionAr: "مشروب مثلج بزبدة الفول السوداني.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-pistachio-cream-blend",
    nameEn: "Pistachio Cream Blend",
    nameAr: "بليند كريمة فستق",
    category: "blended",
    price: 130,
    descriptionAr: "كريمة فستق مع إسبريسو اختياري.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-caramel-blend",
    nameEn: "Caramel Blend",
    nameAr: "بليند كراميل",
    category: "blended",
    price: 120,
    descriptionAr: "كراميل، حليب بودرة، فانيليا وإسبريسو.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-white-mocha-blend",
    nameEn: "White Mocha Blend",
    nameAr: "بليند وايت موكا",
    category: "blended",
    price: 120,
    descriptionAr: "شوكولاتة بيضاء، فانيليا، حليب بودرة وإسبريسو.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-salted-caramel-blend",
    nameEn: "Salted Caramel Blend",
    nameAr: "بليند كراميل مملح",
    category: "blended",
    price: 120,
    descriptionAr: "مشروب مثلج بكراميل مملح.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-mocha-blend",
    nameEn: "Mocha Blend",
    nameAr: "بليند موكا",
    category: "blended",
    price: 120,
    descriptionAr: "شوكولاتة، حليب طازج وإسبريسو.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-latte-blend",
    nameEn: "Latte Blend",
    nameAr: "بليند لاتيه",
    category: "blended",
    price: 100,
    descriptionAr: "حليب طازج، إسبريسو بودرة وثلج.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-spanish-blend",
    nameEn: "Spanish Blend",
    nameAr: "بليند إسباني",
    category: "blended",
    price: 120,
    descriptionAr: "حليب مكثف، إسبريسو، حليب بودرة وفانيليا.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-oreo-nutella-cream",
    nameEn: "Oreo Nutella Cream",
    nameAr: "كريمة أوريو ونوتيلا",
    category: "blended",
    price: 100,
    descriptionAr: "أوريو، نوتيلا وفانيليا بودرة.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-strawberry-vanilla-cream",
    nameEn: "Strawberry Vanilla Cream",
    nameAr: "كريمة فراولة وفانيليا",
    category: "blended",
    price: 100,
    descriptionAr: "فراولة، فانيليا، ثلج وكريمة مخفوقة.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-blueberry-blend",
    nameEn: "Blueberry",
    nameAr: "بلو بيري",
    category: "blended",
    price: 90,
    descriptionAr: "توت أزرق، فانيليا بودرة، ثلج وكريمة.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-matcha-salted-caramel",
    nameEn: "Matcha Salted Caramel",
    nameAr: "ماتشا كراميل مملح",
    category: "tea",
    price: 120,
    descriptionAr: "ماتشا مع كراميل مملح.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-hot-spanish-matcha",
    nameEn: "Hot Spanish Matcha",
    nameAr: "ماتشا إسباني ساخن",
    category: "tea",
    price: 120,
    descriptionAr: "ماتشا إسباني ياباني.",
    temperature: "hot",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-japanese-cream-spanish-matcha",
    nameEn: "Japanese Cream Spanish Matcha",
    nameAr: "ماتشا إسباني كريمي ياباني",
    category: "tea",
    price: 120,
    descriptionAr: "ماتشا ياباني بأسلوب إسباني كريمي.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-japanese-blueberry-matcha-cream",
    nameEn: "Japanese Blueberry Matcha Cream",
    nameAr: "ماتشا توت أزرق كريمي",
    category: "tea",
    price: 120,
    descriptionAr: "ماتشا ياباني مع توت أزرق.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-japanese-iced-white-chocolate-matcha",
    nameEn: "Japanese Iced White Chocolate Matcha",
    nameAr: "ماتشا شوكولاتة بيضاء مثلجة",
    category: "tea",
    price: 120,
    descriptionAr: "ماتشا ياباني بشوكولاتة بيضاء مثلجة.",
    temperature: "iced",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-japanese-matcha-latte",
    nameEn: "Japanese Matcha Latte",
    nameAr: "لاتيه ماتشا ياباني",
    category: "tea",
    price: 120,
    descriptionAr: "ماتشا ياباني كلاسيكي.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-japanese-white-chocolate-matcha-blend",
    nameEn: "Japanese White Chocolate Matcha Blend",
    nameAr: "بليند ماتشا شوكولاتة بيضاء",
    category: "tea",
    price: 120,
    descriptionAr: "ماتشا وشوكولاتة بيضاء.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-japanese-cream-matcha",
    nameEn: "Japanese Cream Matcha",
    nameAr: "ماتشا كريمي ياباني",
    category: "tea",
    price: 120,
    descriptionAr: "ماتشا ياباني مع حليب بودرة وفانيليا.",
    temperature: "room",
    sweetness: "high",
    caffeine: "medium",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-sunshine-red-bull",
    nameEn: "Sunshine Red Bull",
    nameAr: "صن شاين ريد بول",
    category: "drink",
    price: 130,
    descriptionAr: "مكس ريد بول بنكهة صن شاين.",
    temperature: "room",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-red-bull",
    nameEn: "Red Bull",
    nameAr: "ريد بول",
    category: "drink",
    price: 100,
    descriptionAr: "ريد بول.",
    temperature: "room",
    sweetness: "medium",
    caffeine: "high",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-water",
    nameEn: "water",
    nameAr: "مياه",
    category: "drink",
    price: 10,
    descriptionAr: "مياه.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-sunshine-blue-lemonade",
    nameEn: "Sunshine Blue Lemonade",
    nameAr: "صن شاين ليمون أزرق",
    category: "drink",
    price: 80,
    descriptionAr: "ليمون أزرق، ليمون، نعناع وسودا.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-sunshine-strawberry",
    nameEn: "Sunshine Strawberry",
    nameAr: "صن شاين فراولة",
    category: "drink",
    price: 80,
    descriptionAr: "فراولة، ليمون، نعناع وسودا.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-sunshine-peach",
    nameEn: "Sunshine Peach",
    nameAr: "صن شاين خوخ",
    category: "drink",
    price: 80,
    descriptionAr: "خوخ، ليمون، نعناع وسودا.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-sunshine-blueberry",
    nameEn: "Sunshine Blueberry",
    nameAr: "صن شاين توت أزرق",
    category: "drink",
    price: 80,
    descriptionAr: "توت أزرق، ليمون، نعناع وسودا.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-sunshine-passion-fruit",
    nameEn: "Sunshine Passion Fruit",
    nameAr: "صن شاين باشن فروت",
    category: "drink",
    price: 80,
    descriptionAr: "سودا باشن فروت.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-sunshine-lemon-mint",
    nameEn: "Sunshine Lemon Mint",
    nameAr: "صن شاين ليمون ونعناع",
    category: "drink",
    price: 80,
    descriptionAr: "سودا ليمون ونعناع.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-peach-iced-tea",
    nameEn: "Peach Iced Tea",
    nameAr: "شاي خوخ مثلج",
    category: "drink",
    price: 80,
    descriptionAr: "شاي خوخ مثلج بسكر خفيف.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-lemon-passion-fruit",
    nameEn: "Lemon Passion Fruit",
    nameAr: "ليمون باشن فروت",
    category: "drink",
    price: 80,
    descriptionAr: "ليمون وفواكه استوائية بسكر خفيف.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-watermelon",
    nameEn: "watermelon",
    nameAr: "بطيخ",
    category: "drink",
    price: 80,
    descriptionAr: "عصير بطيخ مع ثلج وسكر.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-mango-smoothie",
    nameEn: "Mango smoothie",
    nameAr: "سموذي مانجو",
    category: "drink",
    price: 70,
    descriptionAr: "سموذي مانجو.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-mango",
    nameEn: "Mango",
    nameAr: "مانجو",
    category: "drink",
    price: 60,
    descriptionAr: "عصير مانجو.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-blueberry-smoothie",
    nameEn: "Blueberry Smoothie",
    nameAr: "سموذي توت أزرق",
    category: "drink",
    price: 80,
    descriptionAr: "توت أزرق بري مع ماء.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-passion-fruit-smoothie",
    nameEn: "Passion Fruit Smoothie",
    nameAr: "سموذي باشن فروت",
    category: "drink",
    price: 80,
    descriptionAr: "فواكه استوائية مع ثلج.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-mint-lemonade",
    nameEn: "Mint Lemonade",
    nameAr: "ليمونادة بالنعناع",
    category: "drink",
    price: 60,
    descriptionAr: "ليمونادة، نعناع، ثلج وماء.",
    temperature: "iced",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-fresh-orange-juice",
    nameEn: "Fresh Orange Juice",
    nameAr: "عصير برتقال طازج",
    category: "drink",
    price: 60,
    descriptionAr: "عصير برتقال طازج.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: false,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-blueberry-danish",
    nameEn: "Blueberry Danish",
    nameAr: "دانش توت أزرق",
    category: "dessert",
    price: 120,
    descriptionAr: "طبقات زبدة مع كريمة فانيليا وتوت أزرق.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-red-velvet-cake",
    nameEn: "Red velvet cake",
    nameAr: "كيك ريد فيلفت",
    category: "dessert",
    price: 120,
    descriptionAr: "كيك ريد فيلفت.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-carrot-cake",
    nameEn: "Carrot Cake",
    nameAr: "كيك جزر",
    category: "dessert",
    price: 120,
    descriptionAr: "كيك جزر بالجوز.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-classic-cheesecake",
    nameEn: "Classic Cheesecake",
    nameAr: "تشيز كيك كلاسيك",
    category: "dessert",
    price: 80,
    descriptionAr: "تشيز كيك سادة.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-italian-tiramisu",
    nameEn: "Italian Tiramisu",
    nameAr: "تيراميسو إيطالي",
    category: "dessert",
    price: 120,
    descriptionAr: "تيراميسو كريمي.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-russian-honey-cake",
    nameEn: "Russian Honey Cake",
    nameAr: "كيك عسل روسي",
    category: "dessert",
    price: 90,
    descriptionAr: "كيك عسل روسي.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-chocolate-cake-walnut",
    nameEn: "Chocolate Cake Walnut",
    nameAr: "كيك شوكولاتة بالجوز",
    category: "dessert",
    price: 100,
    descriptionAr: "كيك شوكولاتة بجوز طازج.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-san-sebastian-cheesecake",
    nameEn: "San Sebastian Cheesecake",
    nameAr: "تشيز كيك سان سيباستيان",
    category: "dessert",
    price: 90,
    descriptionAr: "تشيز كيك سان سيباستيان.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-tuna-melt-sandwich",
    nameEn: "Tuna Melt Sandwich",
    nameAr: "ساندوتش تونة ميلت",
    category: "food",
    price: 90,
    descriptionAr: "تونة، خضار، جبنة وخبز أسمر.",
    temperature: "hot",
    sweetness: "low",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-american-donuts",
    nameEn: "American donuts",
    nameAr: "دونات أمريكية",
    category: "food",
    price: 80,
    descriptionAr: "دونات أمريكية.",
    temperature: "hot",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-butter-croissant",
    nameEn: "Butter Croissant",
    nameAr: "كرواسون زبدة",
    category: "food",
    price: 50,
    descriptionAr: "كرواسون زبدة طازج.",
    temperature: "hot",
    sweetness: "low",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-pistachio-croissant",
    nameEn: "Pistachio Croissant",
    nameAr: "كرواسون فستق",
    category: "food",
    price: 100,
    descriptionAr: "كرواسون زبدة مع كريمة فستق.",
    temperature: "hot",
    sweetness: "low",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-sandwich",
    nameEn: "Sandwich",
    nameAr: "ساندوتش",
    category: "food",
    price: 95,
    descriptionAr: "جبنة، دجاج تركي، خس، فلفل ومايونيز.",
    temperature: "hot",
    sweetness: "low",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-turkish-cheese-croissant",
    nameEn: "Turkish Cheese Croissant",
    nameAr: "كرواسون جبنة ودجاج تركي",
    category: "food",
    price: 85,
    descriptionAr: "كرواسون مع جبنة ودجاج تركي وخضار.",
    temperature: "hot",
    sweetness: "low",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-nutella-croissant",
    nameEn: "Nutella Croissant",
    nameAr: "كرواسون نوتيلا",
    category: "food",
    price: 80,
    descriptionAr: "كرواسون زبدة مع نوتيلا.",
    temperature: "hot",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-cinnamon-roll",
    nameEn: "Cinnamon Roll",
    nameAr: "لفة قرفة",
    category: "food",
    price: 80,
    descriptionAr: "لفة قرفة.",
    temperature: "hot",
    sweetness: "low",
    caffeine: "none",
    availability: false,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-nutella-cookies",
    nameEn: "Nutella Cookies",
    nameAr: "كوكيز نوتيلا",
    category: "dessert",
    price: 85,
    descriptionAr: "كوكيز نوتيلا.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-kinder-cookies",
    nameEn: "Kinder Cookies",
    nameAr: "كوكيز كيندر",
    category: "dessert",
    price: 85,
    descriptionAr: "كوكيز كيندر.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-original-cookie",
    nameEn: "Original Cookie",
    nameAr: "كوكيز أوريجينال",
    category: "dessert",
    price: 85,
    descriptionAr: "كوكيز أوريجينال.",
    temperature: "room",
    sweetness: "high",
    caffeine: "none",
    availability: true,
    recommendable: true,
    image: "",
  }),
  menuItem({
    id: "bq-extra-hazelnut",
    nameEn: "Hazelnut",
    nameAr: "بندق",
    category: "extra",
    price: 30,
    descriptionAr: "إضافة بندق.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-extra-oat-milk",
    nameEn: "OAT milk",
    nameAr: "حليب شوفان",
    category: "extra",
    price: 30,
    descriptionAr: "إضافة حليب شوفان.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-extra-coconut-milk",
    nameEn: "coconut milk",
    nameAr: "حليب جوز الهند",
    category: "extra",
    price: 30,
    descriptionAr: "إضافة حليب جوز الهند.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-extra-strawberry",
    nameEn: "Strawberry",
    nameAr: "فراولة",
    category: "extra",
    price: 30,
    descriptionAr: "إضافة فراولة.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-extra-blueberry",
    nameEn: "Blueberry",
    nameAr: "توت أزرق",
    category: "extra",
    price: 30,
    descriptionAr: "إضافة توت أزرق.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-extra-caramel",
    nameEn: "Caramel",
    nameAr: "كراميل",
    category: "extra",
    price: 30,
    descriptionAr: "إضافة كراميل.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-extra-pistachio",
    nameEn: "Pistachio",
    nameAr: "فستق",
    category: "extra",
    price: 35,
    descriptionAr: "إضافة فستق.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-extra-nutella",
    nameEn: "Nutella",
    nameAr: "نوتيلا",
    category: "extra",
    price: 30,
    descriptionAr: "إضافة نوتيلا.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-beans-turkish-coffee",
    nameEn: "Turkish coffee",
    nameAr: "بن قهوة تركي",
    category: "retail",
    price: 270,
    descriptionAr: "خليط برازيلي وكولومبي للقهوة التركية.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-beans-milky-way",
    nameEn: "Milky Way Blend",
    nameAr: "خليط ميلكي واي",
    category: "retail",
    price: 500,
    descriptionAr: "خليط من محصولين برازيلي وكولومبي.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-beans-brazilian",
    nameEn: "Brazilian Coffee",
    nameAr: "بن برازيلي",
    category: "retail",
    price: 550,
    descriptionAr: "بن برازيلي بلاك دايموند.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
  menuItem({
    id: "bq-beans-ethiopian",
    nameEn: "Ethiopian Coffee",
    nameAr: "بن إثيوبي",
    category: "retail",
    price: 650,
    descriptionAr: "بن إثيوبي سبيشيالتي ٢٥٠جم.",
    temperature: "room",
    sweetness: "none",
    caffeine: "none",
    availability: true,
    recommendable: false,
    image: "",
  }),
];

/** Matcha drinks → Blueberry Danish (catalog pairing, not scored guesswork). */
const MATCHA_DESSERT_PAIRING = ["bq-blueberry-danish"];

function withCatalogPairings(products) {
  return products.map((p) => {
    const label = `${p.nameEn ?? ""} ${p.nameAr ?? ""}`;
    if (
      /matcha|ماتشا/i.test(label) &&
      (!p.dessertPairing || p.dessertPairing.length === 0)
    ) {
      return { ...p, dessertPairing: MATCHA_DESSERT_PAIRING };
    }
    return p;
  });
}

export const products = withCatalogPairings(rawProducts);
